[2019-04-17 10:34:49] INFO [<module>: run.py, 13] ---------测试开始---------------
[2019-04-17 10:34:49] DEBUG [_new_conn: connectionpool.py, 208] Starting new HTTP connection (1): 115.28.108.130
[2019-04-17 10:34:50] DEBUG [_make_request: connectionpool.py, 396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-17 10:34:50] INFO [log_case_info: basecase.py, 11] 测试用例:test_user_login_normal
[2019-04-17 10:34:50] INFO [log_case_info: basecase.py, 13] method:POST
[2019-04-17 10:34:50] INFO [log_case_info: basecase.py, 14] 请求参数:{"name": "张三","password":"123456"}
[2019-04-17 10:34:50] INFO [log_case_info: basecase.py, 16] 预期结果:<h1>登录成功</h1>
[2019-04-17 10:34:50] INFO [log_case_info: basecase.py, 17] 实际结果:<h1>登录成功</h1>
[2019-04-17 10:34:50] DEBUG [_new_conn: connectionpool.py, 208] Starting new HTTP connection (1): 115.28.108.130
[2019-04-17 10:34:50] DEBUG [_make_request: connectionpool.py, 396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-17 10:34:50] INFO [log_case_info: basecase.py, 11] 测试用例:test_user_login_password_wrong
[2019-04-17 10:34:50] INFO [log_case_info: basecase.py, 13] method:POST
[2019-04-17 10:34:50] INFO [log_case_info: basecase.py, 14] 请求参数:{"name": "张三","password":"1234567"}
[2019-04-17 10:34:50] INFO [log_case_info: basecase.py, 16] 预期结果:<h1>失败，用户名或密码错误</h1>
[2019-04-17 10:34:50] INFO [log_case_info: basecase.py, 17] 实际结果:<h1>失败，用户名或密码错误</h1>
[2019-04-17 10:34:51] INFO [send_email: email_conf.py, 33] -----------开始发送邮件----------
[2019-04-17 10:34:51] INFO [send_email: email_conf.py, 35] -----------邮件发送完成！-----------
[2019-04-17 10:34:51] INFO [<module>: run.py, 27] --------------测试结束---------------
[2019-04-17 10:45:17] INFO [<module>: run.py, 13] ---------测试开始---------------
[2019-04-17 10:45:17] DEBUG [_new_conn: connectionpool.py, 208] Starting new HTTP connection (1): 115.28.108.130
[2019-04-17 10:45:17] DEBUG [_make_request: connectionpool.py, 396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-17 10:45:17] INFO [log_case_info: basecase.py, 11] 测试用例:test_user_login_normal
[2019-04-17 10:45:17] INFO [log_case_info: basecase.py, 13] method:POST
[2019-04-17 10:45:17] INFO [log_case_info: basecase.py, 14] 请求参数:{"name": "张三","password":"123456"}
[2019-04-17 10:45:17] INFO [log_case_info: basecase.py, 16] 预期结果:<h1>登录成功</h1>
[2019-04-17 10:45:17] INFO [log_case_info: basecase.py, 17] 实际结果:<h1>登录成功</h1>
[2019-04-17 10:45:17] DEBUG [_new_conn: connectionpool.py, 208] Starting new HTTP connection (1): 115.28.108.130
[2019-04-17 10:45:17] DEBUG [_make_request: connectionpool.py, 396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-17 10:45:17] INFO [log_case_info: basecase.py, 11] 测试用例:test_user_login_password_wrong
[2019-04-17 10:45:17] INFO [log_case_info: basecase.py, 13] method:POST
[2019-04-17 10:45:17] INFO [log_case_info: basecase.py, 14] 请求参数:{"name": "张三","password":"1234567"}
[2019-04-17 10:45:17] INFO [log_case_info: basecase.py, 16] 预期结果:<h1>失败，用户名或密码错误</h1>
[2019-04-17 10:45:17] INFO [log_case_info: basecase.py, 17] 实际结果:<h1>失败，用户名或密码错误</h1>
[2019-04-17 10:45:17] INFO [<module>: run.py, 28] --------------测试结束---------------
[2019-04-17 10:46:05] INFO [<module>: run.py, 13] ---------测试开始---------------
[2019-04-17 10:46:05] DEBUG [_new_conn: connectionpool.py, 208] Starting new HTTP connection (1): 115.28.108.130
[2019-04-17 10:46:05] DEBUG [_make_request: connectionpool.py, 396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-17 10:46:05] INFO [log_case_info: basecase.py, 11] 测试用例:test_user_login_normal
[2019-04-17 10:46:05] INFO [log_case_info: basecase.py, 13] method:POST
[2019-04-17 10:46:05] INFO [log_case_info: basecase.py, 14] 请求参数:{"name": "张三","password":"123456"}
[2019-04-17 10:46:05] INFO [log_case_info: basecase.py, 16] 预期结果:<h1>登录成功</h1>
[2019-04-17 10:46:05] INFO [log_case_info: basecase.py, 17] 实际结果:<h1>登录成功</h1>
[2019-04-17 10:46:05] DEBUG [_new_conn: connectionpool.py, 208] Starting new HTTP connection (1): 115.28.108.130
[2019-04-17 10:46:05] DEBUG [_make_request: connectionpool.py, 396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-17 10:46:05] INFO [log_case_info: basecase.py, 11] 测试用例:test_user_login_password_wrong
[2019-04-17 10:46:05] INFO [log_case_info: basecase.py, 13] method:POST
[2019-04-17 10:46:05] INFO [log_case_info: basecase.py, 14] 请求参数:{"name": "张三","password":"1234567"}
[2019-04-17 10:46:05] INFO [log_case_info: basecase.py, 16] 预期结果:<h1>失败，用户名或密码错误</h1>
[2019-04-17 10:46:05] INFO [log_case_info: basecase.py, 17] 实际结果:<h1>失败，用户名或密码错误</h1>
[2019-04-17 10:46:06] INFO [send_email: email_conf.py, 33] -----------开始发送邮件----------
[2019-04-17 10:46:07] INFO [send_email: email_conf.py, 35] -----------邮件发送完成！-----------
[2019-04-17 10:46:07] INFO [<module>: run.py, 28] --------------测试结束---------------
[2019-04-17 10:50:54] INFO [<module>: run.py, 13] ---------测试开始---------------
[2019-04-17 10:52:01] INFO [<module>: run.py, 13] ---------测试开始---------------
[2019-04-17 10:53:46] INFO [<module>: run.py, 13] ---------测试开始---------------
[2019-04-17 10:53:46] DEBUG [_new_conn: connectionpool.py, 208] Starting new HTTP connection (1): 115.28.108.130
[2019-04-17 10:53:46] DEBUG [_make_request: connectionpool.py, 396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-17 10:53:46] INFO [log_case_info: basecase.py, 11] 测试用例:test_user_login_normal
[2019-04-17 10:53:46] INFO [log_case_info: basecase.py, 13] method:POST
[2019-04-17 10:53:46] INFO [log_case_info: basecase.py, 14] 请求参数:{"name": "张三","password":"123456"}
[2019-04-17 10:53:46] INFO [log_case_info: basecase.py, 16] 预期结果:<h1>登录成功</h1>
[2019-04-17 10:53:46] INFO [log_case_info: basecase.py, 17] 实际结果:<h1>登录成功</h1>
[2019-04-17 10:53:46] DEBUG [_new_conn: connectionpool.py, 208] Starting new HTTP connection (1): 115.28.108.130
[2019-04-17 10:53:46] DEBUG [_make_request: connectionpool.py, 396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-17 10:53:46] INFO [log_case_info: basecase.py, 11] 测试用例:test_user_login_password_wrong
[2019-04-17 10:53:46] INFO [log_case_info: basecase.py, 13] method:POST
[2019-04-17 10:53:46] INFO [log_case_info: basecase.py, 14] 请求参数:{"name": "张三","password":"1234567"}
[2019-04-17 10:53:46] INFO [log_case_info: basecase.py, 16] 预期结果:<h1>失败，用户名或密码错误</h1>
[2019-04-17 10:53:46] INFO [log_case_info: basecase.py, 17] 实际结果:<h1>失败，用户名或密码错误</h1>
[2019-04-17 10:53:47] INFO [send_email: email_conf.py, 33] -----------开始发送邮件----------
[2019-04-17 10:53:48] INFO [send_email: email_conf.py, 35] -----------邮件发送完成！-----------
[2019-04-17 10:53:48] INFO [<module>: run.py, 28] --------------测试结束---------------
